org: akaviles024
app: node-lambda-1
service: node-lambda-1
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId:
      "Fn::ImportValue": SharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": SharedGW-rootResourceId

functions:
  products:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
