org: akaviles024
app: node-lambda-1
service: node-lambda-1
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  apiGateway:
    restApiId: ${cf:shared-gateway-dev.apiGatewayRestApiId}
    restApiRootResourceId: ${cf:shared-gateway-dev.apiGatewayRestApiRootResourceId}

functions:
  products:
    handler: index.handler
    events:
      - http:
          path: products
          method: get
