org: akaviles024
app: node-lambda-1
service: node-lambda-1
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId: 1sv4m5x2jl
    restApiRootResourceId: qoseq49m7l

functions:
  products:
    handler: index.handler
    events:
      - httpApi:
          path: products
          method: get
